# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- sonartest

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mikeo7-github'
    scannerMode: 'CLI'
    configMode: 'file'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm install -g sonarqube-scanner
  displayName: 'install scanner'

- script: |
    sonar-scanner \
      -Dsonar.projectKey=MikeO7_pipelines-javascript \
      -Dsonar.organization=mikeo7-github \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=1644a044754ef09d676277bde6b30af39693a62b
  displayName: 'install scanner'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'